### ISSUE TITLE
Can't view from the repository with SourceTree

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/anupq#4]
I've made a fresh clone, but I still can't view the repository with SourceTree. Any ideas? Thanks.

![anupq-repo-bug](https://f.cloud.github.com/assets/5751387/1857860/3509dc66-7781-11e3-869b-d658c4f6bdd0.png)

**Comment by fingolfin** [comment]
Perhaps the version of SourceTree you were using got confused by the present of the .hgignore file, a leftover from the days when the repository was a Mercurial repository. As such, it would be a bug in SourceTree, albeit one that does not occur for me with SourceTree 2.0.4. I am going to remove the .hgignore file; but in any case, I am afraid there is nothing else we can do about this, should the issue is persist for you.
